Add plug in provider info
music-assistant/music-assistant.io pull request #28
Opened 2024-02-21 09:31 UTC by OzGav

2024-02-21 20:53 UTC, jozefKruszynski commented on docs/index.md
> +    - A optional sub-component of the Integraton is the Home Assistant Plugin for Music Assistant. This allows the importing of Home Assistant media players into the Music Assistant engine to use as
```suggestion
    - An optional sub-component of the Integraton is the Home Assistant Plugin for Music Assistant. This allows the importing of Home Assistant media players into the Music Assistant engine to use as targets for playback
```

2024-02-21 20:54 UTC, jozefKruszynski requested changes
Small issue

2024-02-21 22:11 UTC, OzGav commented
Love your eagle eye. Fixed.

2024-02-22 05:50 UTC, jozefKruszynski approved these changes

2024-02-22 05:50 UTC, merged